### ISSUE TITLE
Sample code

### ISSUE THREAD

**Issue by dipongkor** [koltyakov/sp-live-reload#2]
Hi,

This is not any issue. I am writing here just to communicate with you.

I want to use this for my content editor web part development.

Can you help with a sample code?

Thanks 
Atish

**Comment by koltyakov** [comment]
Hi,

It should be pretty easy, there is an example in the readme for usage with [spsave](https://github.com/koltyakov/sp-live-reload/blob/master/README.md#watch-with-live-reload-spsave) and [gulp-spsync](https://github.com/koltyakov/sp-live-reload#watch-with-live-reload-gulp-spsync).

Also, I would recommend trying [generator-sppp](https://github.com/koltyakov/generator-sppp) which creates scaffolding project equipped with basic tasks for delivering scripts into SharePoint tenant including watching with live reload.

Are you going to deal with On-Premises or SharePoint Online? In a case of SPO, don't forget about SSL certificate for trusting local https server.
