### ISSUE TITLE
Adding example config file for sp-live-reload

### ISSUE THREAD

**Issue by Nikita-schetko** [koltyakov/sp-live-reload#4]
Hi Andrew! Could i ask you to add sample config file for sp-live-reload ? It's very difficult to understand all necessery arguments for proper module working at the first time.
Thank you in advance!

**Comment by koltyakov** [comment]
Hi Nikita,

Thanks for your input.

The module is integrated into [generator-sppp](https://github.com/koltyakov/generator-sppp) Yeoman generator with use of [sp-build-tasks](https://github.com/koltyakov/sp-build-tasks). In some scenarios, it can be easier to grab generator-sppp. 

After creating a new project with `yo sppp` and providing prompts for credentials by running `gulp config`, all you need then is to deliver `sp-live-reload` client to a specific page (adding `<script src='...'></script>` with the url to reload local server) or globally to the web (by running `gulp reload:install` - this install script link custom action) and run watch task with live reload `gulp live`.

For stand alone usage the config should correspond to:

```javascript
export interface ILRSettings {
    siteUrl: string;
    spFolder: string;
    watchBase: string;
    creds: IAuthOptions;
    ssl?: ISSLConf;
    port?: number;
    host?: string;
    protocol?: 'https' | 'http';
}
```

So the only really required params are:
- siteUrl: string - SharePoint SPWeb absolute URL
- spFolder: string - relative - relative folder URL where you going to upload assets with SPSave or SPSync
- watchBase: string - path.join(process.cwd(), distFolder.replace('./', '')), where `distFolder` is a relative path to local folder with assets, e.g. `./src`
- creds: IAuthOptions - authentication options, can be seen [here](https://github.com/s-KaiNet/node-sp-auth#params)

Maybe a bit overcomplicated for stand alone usage.
Will take a look how to make the documentation more straightforward.

And once again, my recommendation is to try the module using generator-sppp first. This guy makes it really simple.

**Comment by koltyakov** [comment]
Closing the issue due to inactivity. Feel tree to reopen in case of questions.
