### ISSUE TITLE
Can it be used for on prem environment from client computer ?

### ISSUE THREAD

**Issue by seaSide974** [koltyakov/sp-live-reload#5]
hi, i have on prem servers hosted in my company network, explorer view works sometime and sometimes no.
Can I use this tool to upload files in style library and live reload whenever one change ?
Can I use it for multiple environment, example, to see a change on DEV + UAT at the same time ? 

thx a lot 👍

**Comment by koltyakov** [comment]
Hey Jeff,

Thanks for posting the question and the interest using the library. 

I wondering what do you mean by “explorer view works sometimes and sometimes no”?

Do you mean that during updating some assets you experience that page with assets does not reload?

Live reload definitely works with SharePoint 2013 and 2016, as well as with SPO. Yet, it is not in charge for uploading the files, only emiting a signal that something has been updated on reload server and detecting that this asset is presented on the page using live reload client script. 

Live reloading of multiple tenanses’ pages is possible but requires additional setup and configuration. I’ve never needed simultaneous deployment to DEV and UAT environments. Or even using live reload somethere but not a DEV environment. 

I would recommend trying [generator-sppp](https://github.com/koltyakov/generator-sppp) it allows creating scaffolded project with a bunch of possible build tasks including assets uploading with preconfigured live reload.

—
Andrew

**Comment by seaSide974** [comment]
Thanks for your quick and detailed answer.
I meant that I upload my js and css using the windows explore view of the site assets library. Then I edit those files from visual code.
I wonder, how to do you push your changes to the server ? I dont understand the flow of the process with the live reload for files changed on the local disk...

Thank you,

**Comment by koltyakov** [comment]
Oh, I got your question.

This is not gonna work this way until you make this mapped folder watched and emit signals about files changes. Which is kind of hairy in case of the mapped drive. Also mapped drive causes some serious issues in the development workflow (it's not stable, requires IE, crashes, causes auth problems, publishing versions hassles).

`sp-live-reload` was designed to work in combination with such libraries as `spsave`.

The flow is following:

- Local folder project (with source control enabled) is edited in an IDE/editor of choice, e.g. VS Code;
- Dist folder is configured to be watched files for changes (for instance with gulp watch);
- During watch assets tasks a live reload local server is started on a developer's machine;
  - Live reload uses sockets to talk to the client script located on SharePoint page(s);
  - Client script monitors for update signals and if the received path is somewhere on the page (masterpage, layout, CEWP source link, styles, scripts) and initiate page reload or styles update;
  - Live reload server has an API / events for emitting a changed file pathname.
- On file change, gulp/grunt/webpack/npm task uploads changed file to target SharePoint folder (_catalogs/masterpage, SiteAssets, Style Library, etc.) taking care of publishing it;
  - spsave/gult-spsave is a perfect tools for this part;
- Right after the file is uploaded live reload's API should be informed to emit a message for a client script.

Here is an example of the gulp task doing the job:

```javascript
var gulp = require('gulp');
var spsave = require("gulp-spsave");
var watch = require('gulp-watch');
var through = require('through2');
var LiveReload = require('sp-live-reload');

var config = require('./gulp.config');

gulp.task("watch-assets", function () {
    console.log("Watch with reload is initiated.");
    console.log("Make sure that monitoring script is provisioned to SharePoint.");
    var liveReload = new LiveReload(config);
    liveReload.runServer();
    return watch(config.watchAssets, function (event) {
        console.log(event.path);
        gulp.src(event.path, {
            base: config.watchBase
        }).pipe(spsave(config.spsaveCoreOptions, config.spsaveCreds))
        .pipe(through.obj(function (chunk, enc, cb) {
            var chunkPath = chunk.path;
            liveReload.emitUpdatedPath(chunkPath);
            cb(null, chunk);
        }));
    });
});
```

Some details can be found in this blog post [SharePoint client-side development with Live Reload](https://www.linkedin.com/pulse/sharepoint-client-side-development-live-reload-andrew-koltyakov).

Configuring the tasks and libs can be tough and time-consuming, to avoid this and make the process as simple as possible the generator project mentioned above was created, which I definitely recommend starting with.

**Comment by seaSide974** [comment]
Hi,

Ah thank you ! that clarifies a lot my understanding of this project.

I will give it a try thanks to the detailed information you provided !

For information, opening the files (javascript, css etc) from the windows explorer view, works well as long as versioning and file checkout are disable on the library (i personnaly drop the files in style library). 
Then i edit the file in visual studio code and reload manually chrome or IE to see the updated code. Though a live reload would be great.

Have a great day,

Jeff

**Comment by koltyakov** [comment]
> opening the files (javascript, css etc) from the windows explorer view, works well as long as versioning and file checkout are disable on the library (i personnaly drop the files in style library)

Sure thing. But this is kind of risky losing changes.
I always enable versioning in assets libraries to keep track of changes, especially if more than one dev is in charge of changes.
Also, as a project source always MUST be in reliable source control like Git using the direct opening of files in explorer and WebDAV it's even riskier. Beleive me, as we went through this stage years ago before investing into creating a toolchain. ;)

**Comment by seaSide974** [comment]
Yes that is the downside of my method, no source control. So i manually create a backup each major feature.
I disabled the versioning because after more than 200 saves i think the file do not save anymore :)

**Comment by koltyakov** [comment]
Closing this. Feel free to reopen.
