### ISSUE TITLE
cant get it work in my project

### ISSUE THREAD

**Issue by seaSide974** [koltyakov/sp-live-reload#8]
hi  !

where is the config file called for : 
let config = require('./config');

?

I am using spsynch for info and trying to integrate this 

thx

**Comment by koltyakov** [comment]
Hey Jeff,

Live reload expects [following parameters](https://github.com/koltyakov/sp-live-reload/blob/master/src/interfaces/index.ts#L8):

```TypeScript
export interface ILRSettings {
  siteUrl: string;
  spFolder: string;
  watchBase: string;
  creds: IAuthOptions;
  ssl?: ISSLConf;
  port?: number;
  host?: string;
  protocol?: 'https' | 'http';
}
```

Other settings should be according to your build tasks.
You could check [sp-build-tasks](https://github.com/koltyakov/sp-build-tasks) and [generator-sppp](https://github.com/koltyakov/generator-sppp) as complete examples how this can be bind together.

**Comment by seaSide974** [comment]
thx ! im using javascript code and gulpsynch to push my js to the sharepoint 2013 on prem. Maybe its time for me to move to typescript / pnp :)
Do you have any suggestion as starter bundle to get this done ? I guess this would be easier to setup the livereload :) ?

**Comment by koltyakov** [comment]
Hey Jeff,

I would recommend trying [generator-sppp](https://github.com/koltyakov/generator-sppp).
It creates a scaffolded project powered with tasks for SharePoint 2013 (as well as 2016, SPO) development:
- webparts (CEWP containers are created with Handlebars (.hbs) with dynamic project's variables injected)
- layouts/masterpages
- javascript (TypeScript, .tsx, JavasScript, .jsx are supported) - from the start you can write in typescript, or apply a small change and switched to ES6 for example
- css - generator uses SCSS, any css is a valid SCSS

Tasks include such actions as:
- build (prepare publishable Dist folder)
- watch, including Live Reload
- deploy to SharePoint
- download assents from SharePoint lib
- and some more

Ping me in Gitter if you wish. We can catch up with remote sharing. I love talking about this generator's features. Actually, all our team uses it on daily basis.

Closing this issue as answered. Tty.
