### ISSUE TITLE
Cannot read property 'hasOwnProperty' of undefined in live-reload.client.js

### ISSUE THREAD

**Issue by leunardo** [koltyakov/sp-live-reload#9]
After setting up the site and opening the console this error shows up:
![image](https://user-images.githubusercontent.com/22580233/39550525-ed55d75c-4e37-11e8-853c-0f74367a86e9.png)

The problem was this statement:
```
 [Element.prototype, CharacterData.prototype, DocumentType.prototype].forEach(function(t) {
        // t is undefined, precisely Document.Type.prototype
        t.hasOwnProperty("after") || Object.defineProperty(t, "after", { 
             [...]
        })
    })
```

Do you have any idea why is this happening? I am using Chrome

**Comment by koltyakov** [comment]
Hey @leunardo,

Thanks for the issue report!
In Chrome I can't reproduce, reload works for styles, JS, source links, masterpage and layouts as well.

But, in IE11 (IE10 compatibility mode) the similar issue with `.after` polyfill.

**Comment by leunardo** [comment]
Hmm, I tested `DocumentType.prototype` in other webpages and it worked. This seems to be a problem with our environment, because independently of the site's host, the `DocumentType.prototype` is undefined when using some of our pages, so I'm closing this issue, thanks for reply!
